### PR TITLE
Infer labels owner and repo from git in cwd for fetch command as per #5

### LINKED ISSUE #5: Infer labels owner and repo from git in working directory
Currently fetching and syncing labels with a GitHub repository requires the ``--repo`` and ``--owner`` CLI options. I think it would be awesome if we could infer this information from the current working directory and the corresponding Git repository 😃 

```text
labels fetch
```

```text
labels sync
```

### PR DESCRIPTION
**Pull request by mfonism**
This PR fixes #5  only for the __fetch__ command.

<del>TO DO: Fix for the __sync__ command.</del>

__UPDATE__: This PR now fixes #5 for __both__ commands, _fetch_ and _sync_.

### CODE REVIEW

**Comment by mfonism** [comment]
__UPDATE__

This PR now fixes #5 for the both commands, __fetch__ and __sync__.

**Comment by mfonism** [comment]
@hackebrot could you please take a look at this PR.

**Comment by hackebrot** [comment]
Hi @mfonism! 👋 

Thank you for working on this. I'll review your changes by the end of my day.

**Comment by hackebrot** [comment]
Hi @mfonism! 🙂 

Apologies this is taking so long. A few things have popped up at work and while I have reviewed your pull-request, I didn't have time to write up proper feedback.

Again, I appreciate your efforts in implementing this feature. 📝

**Comment by mfonism** [comment]
Okay @hackebrot, I understand.

I'll just patiently wait for it. 🙂

**Comment by hackebrot** [comment]
Thank you for your work on this feature @mfonism! 😃 

I merged your changes and refactored the project afterwards. Please feel free to ask, if you have any questions about how the code is organized. 📝

**Comment by mfonism** [comment]
Okay @hackebrot

Thank you for accepting my PR. It's really a confidence boost.

I'll study the project with regards to the new code organization.

And, please, on what medium do I ask you questions that may arise?
Here on Github? Twitter? Email? Slack?

**Comment by hackebrot** [comment]
Please ask any questions related to the labels code here on GitHub, so the information is publicly available for folks who might have similar questions. For anything that you would rather ask in private, please send me an email. 📥

**Pull request merged**
